### ISSUE TITLE
 DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic

### ISSUE THREAD

**Issue by bonesoul** [at0g/nunjucks-loader#55]
```
(node:12084) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (E:\Coding\vapingdb\node_modules\nunjucks-loader\node_modules\loader-utils\index.js:78:3)
    at Object.module.exports (E:\Coding\vapingdb\node_modules\nunjucks-loader\index.js:28:33)
    at LOADER_EXECUTION (E:\Coding\vapingdb\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (E:\Coding\vapingdb\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (E:\Coding\vapingdb\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (E:\Coding\vapingdb\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (E:\Coding\vapingdb\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:15)
    at E:\Coding\vapingdb\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:69:9
    at E:\Coding\vapingdb\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)
```

**Comment by aclaes** [comment]
We have the save issue here

**Comment by YukSeungChan** [comment]
+1
